#!/bin/sh
#
cd {{pkg.svc_var_path}}

export MONGO_URL=mongodb://localhost:27017/todos;
export ROOT_URL=http://localhost;
export PORT=3030;

# `exec` makes it so the process that the Habitat supervisor uses is 
# 'node main.js`, rather than the run hook itself.

# `2>&1` makes it so both standard output and standard error go to the standard 
# output stream, so all the logs from the application go to the same place.

exec node main.js 2>&1

